### ISSUE TITLE
Issue with PowerShell 7

### ISSUE THREAD

**Issue by ykuijs** [gaelcolas/DscBuildHelpers#20]
The module manifest states that xDSCResourceDesigner v1.9.0.0 is tested:
https://github.com/gaelcolas/DscBuildHelpers/blob/664f5fe2b3dd3f25b727281a9837a0c8c60f71e4/source/DscBuildHelpers.psd1#L17

I just ran into an issue where v1.13.0.0 was downloaded under PowerShell 7 and somehow that version can't be loaded in PSv7. v1.9.0.0 works without issues.

Would it be an idea to change the ModuleVersion parameter to RequiredVersion, so v1.9.0.0 is always used?

**Comment by ykuijs** [comment]
Never mind, this was an issue with ModuleFast. That has a bug that is removing the last .0 in the version number in the folder name. This caused loading the module to fail.

After adding the extra .0 in the folder name, the issue was resolved.

**Comment by raandree** [comment]
@ykuijs, is the bug in ModuleFast going to be fixed?

**Comment by ykuijs** [comment]
The author says he will investigate, so I guess it will.

https://github.com/JustinGrote/ModuleFast/issues/98
